### ISSUE TITLE
Plot for estimate_semipmetric_erf and True ERF for generated synthetic data

### ISSUE THREAD

**Issue by jennyjyounglee** [NSAPH-Software/CausalGPS#137]
1. Add plot function for estimate_semipmetric_erf.R.
2. Add true exposure response curve from the generated data using generate_syn_data.R so that users can compare true ERF vs estimated ERF using the example data.

**Comment by Naeemkh** [comment]
Hi @jennyjyounglee, 
I will add this to the enhancement and add the plotting methods soon.
In a real dataset, we do not have the true value. Because of that, we do not include it in the main functions. One can add it on top of the main plot. 
Please see the following vignette for more details.
https://nsaph-software.github.io/GPCERF/articles/Nearest-neighbor-Gaussian-Processes.html

**Comment by m-qin** [comment]
Hello! I'm wondering if the plot function has been added to `estimate_semipmetric_erf()` yet? I am trying to run a `estimate_semipmetric_erf()` model on my data and would love to plot the ERF, but unfortunately I'm running into an error ("'data' must be a data.frame, environment, or list"). Not sure if this is a bug in the code I wrote or just a feature that hasn't been added yet!

**Comment by daniellebraun** [comment]
@Naeemkh @wxwx1993

**Comment by Naeemkh** [comment]
Closing this issue, @jennyjyounglee, please reopen it if you want to work on it.
